import pytest
from v0_1.chunk_image_mapper import (
    _is_structural_noise,
    _is_legitimate_domain_content,
    classify_chunk_depth,
)

# --- Positive Non-CS Domain Prose (Must be legitimate and NOT EXTERNAL) ---

CIVIL_CONCRETE_PROSE = (
    "Slump cone testing determines the consistency and plastic deformation capability of fresh concrete batches. "
    "Excessive water addition increases workability but drastically reduces compressive strength upon curing, "
    "leading to shrinkage cracks, aggregate segregation, and reduced durability in reinforced structural elements."
)

MECH_THERMO_PROSE = (
    "In an ideal Rankine reheat cycle, steam expands through the high-pressure turbine before returning to the boiler. "
    "Reheating increases the quality of steam at the low-pressure turbine exhaust, preventing moisture droplet erosion "
    "on blades while improving overall thermal efficiency."
)

BIOTECH_GENE_PROSE = (
    "Restriction endonucleases cleave phosphodiester bonds at specific palindromic recognition sequences within DNA. "
    "Sticky ends generated by staggered digestion enable ligation into plasmid expression vectors using T4 DNA ligase, "
    "facilitating recombinant protein production in bacterial host cells."
)

ENVIRONMENTAL_BOD_PROSE = (
    "Biochemical Oxygen Demand measures the quantity of dissolved oxygen consumed by aerobic microorganisms "
    "during the biological stabilization of organic matter in wastewater. High BOD values in discharged effluent "
    "cause rapid oxygen depletion in receiving aquatic ecosystems."
)

# --- Negative Structural Noise & Boilerplate (Must be detected as noise and EXTERNAL) ---

TOC_CHUNK = (
    "Table of Contents\n"
    "Module 1: Basic Principles ................................ 12\n"
    "Module 2: Structural Mechanics ............................ 45\n"
    "Module 3: Fluid Dynamics .................................. 89\n"
    "Module 4: Heat Transfer ................................... 134\n"
    "Module 5: Numerical Methods ............................... 180"
)

COPYRIGHT_CHUNK = (
    "Copyright © 2026 Academic Press Inc. All rights reserved.\n"
    "No part of this publication may be reproduced, stored in a retrieval system, "
    "or transmitted in any form without prior written permission of the publisher.\n"
    "ISBN 978-0-12-345678-9. Printed in India."
)

BIBLIOGRAPHY_CHUNK = (
    "[1] Anderson, J. D., Modern Compressible Flow with Historical Perspective, McGraw-Hill, 2020.\n"
    "[2] Incropera, F. P., Fundamentals of Heat and Mass Transfer, John Wiley & Sons, 2018.\n"
    "[3] Cengel, Y. A., Fluid Mechanics: Fundamentals and Applications, Tata McGraw-Hill, 2019."
)

PAGE_HEADER_NOISE = (
    "Page 45 of 210\n"
    "Downloaded from university-portal.edu.in by IP 192.168.1.100\n"
    "Course Material - For Internal Academic Circulation Only"
)


def test_civil_engineering_content_is_core():
    assert not _is_structural_noise(CIVIL_CONCRETE_PROSE)
    assert _is_legitimate_domain_content(CIVIL_CONCRETE_PROSE)
    assert classify_chunk_depth(CIVIL_CONCRETE_PROSE) == "CORE"


def test_mechanical_engineering_content_is_core():
    assert not _is_structural_noise(MECH_THERMO_PROSE)
    assert _is_legitimate_domain_content(MECH_THERMO_PROSE)
    assert classify_chunk_depth(MECH_THERMO_PROSE) == "CORE"


def test_biotechnology_content_is_core():
    assert not _is_structural_noise(BIOTECH_GENE_PROSE)
    assert _is_legitimate_domain_content(BIOTECH_GENE_PROSE)
    assert classify_chunk_depth(BIOTECH_GENE_PROSE) == "CORE"


def test_environmental_content_is_core():
    assert not _is_structural_noise(ENVIRONMENTAL_BOD_PROSE)
    assert _is_legitimate_domain_content(ENVIRONMENTAL_BOD_PROSE)
    assert classify_chunk_depth(ENVIRONMENTAL_BOD_PROSE) == "CORE"


def test_table_of_contents_is_external_noise():
    assert _is_structural_noise(TOC_CHUNK)
    assert not _is_legitimate_domain_content(TOC_CHUNK)
    assert classify_chunk_depth(TOC_CHUNK) == "EXTERNAL"


def test_copyright_disclaimer_is_external_noise():
    assert _is_structural_noise(COPYRIGHT_CHUNK)
    assert not _is_legitimate_domain_content(COPYRIGHT_CHUNK)
    assert classify_chunk_depth(COPYRIGHT_CHUNK) == "EXTERNAL"


def test_bibliography_is_external_noise():
    assert _is_structural_noise(BIBLIOGRAPHY_CHUNK)
    assert not _is_legitimate_domain_content(BIBLIOGRAPHY_CHUNK)
    assert classify_chunk_depth(BIBLIOGRAPHY_CHUNK) == "EXTERNAL"


def test_page_header_is_external_noise():
    assert _is_structural_noise(PAGE_HEADER_NOISE)
    assert not _is_legitimate_domain_content(PAGE_HEADER_NOISE)
    assert classify_chunk_depth(PAGE_HEADER_NOISE) == "EXTERNAL"
